<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Wallpaper extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Wallpaper_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {

            $data = array(
                'action'        => site_url('wallpaper/update_action'),
	    );
            $this->template->load('template','wallpaper/index', $data);
    } 
 
    public function update_action() 
    {
        $this->delete_wallpaper("./img/candyhouse1.jpg");
        $this->delete_wallpaper("./img/candyhouse2.jpg");
        $this->delete_wallpaper("./img/candyhouse3.jpg");
        $this->load->library('upload');

        for ($i = 1; $i <= 3; $i++) : 
            $config['upload_path']          = './img';
            $config['allowed_types']        = 'gif|jpg|png';
            $config['file_name'] = 'candyhouse'.$i.'.jpg';
            $this->upload->initialize($config);
            $this->upload->do_upload('images'.$i);
        endfor;
        redirect(site_url('wallpaper'));
    }
    
    public function delete_wallpaper($path) 
    {
        unlink($path);
    }

}

/* End of file Tbl_user_profile.php */
/* Location: ./application/controllers/Tbl_user_profile.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-12-27 12:33:39 */
/* http://harviacode.com */